# Task: Computer Vision - Vehicle RC reading

In [1]:
import pytesseract   #Python-tesseract is an optical character recognition (OCR) tool for python. It will recognize and “read” the text embedded in images.
import pandas as pd
from PIL import Image,ImageEnhance
import os
pytesseract.pytesseract.tesseract_cmd = r"/opt/homebrew/Cellar/tesseract/4.1.1/bin/tesseract"

In [2]:
PATH = '../richajha/Intern/RC'

list = os.listdir(PATH)     # Making a list(name = list) which holds the names of all images in RC folder.
for i in range(len(list)):
    print(i,list[i])

0 txt_mudit_b11_1334.jpg
1 txt_mudit_b8_1_573.jpg
2 txt_mudit_b11_1337.jpg
3 txt_mudit_b8_1_808.jpg
4 txt_mudit_b8_1_571.jpg
5 txt_mudit_b11_1524.jpg
6 txt_mudit_b11_1332.jpg
7 txt_mudit_b8_1_574.jpg
8 txt_mudit_b11_1534.jpg
9 txt_mudit_b11_1535.jpg
10 txt_mudit_b11_1536.jpg
11 txt_mudit_b11_1330.jpg
12 txt_mudit_b11_1343.jpg
13 txt_mudit_b11_439.jpg
14 txt_mudit_b8_1_854.jpg
15 txt_mudit_b8_1_855.jpg
16 txt_mudit_b11_1354.jpg
17 txt_mudit_b11_12.jpg
18 txt_mudit_b8_1_513.jpg
19 txt_mudit_b11_1355.jpg
20 txt_mudit_b11_1369.jpg
21 txt_mudit_b11_11599.jpg
22 txt_mudit_b11_1347.jpg
23 txt_mudit_b8_2_213.jpg
24 txt_mudit_b11_1362.jpg
25 txt_mudit_b11_746.jpg
26 txt_mudit_b11_961.jpg
27 txt_mudit_b11_1363.jpg
28 txt_mudit_b11_1361.jpg
29 txt_mudit_b11_11597.jpg
30 txt_mudit_b11_1364.jpg
31 txt_mudit_b11_1365.jpg
32 txt_mudit_b8_1_546.jpg
33 txt_mudit_b11_1328.jpg
34 txt_mudit_b11_1539.jpg
35 txt_mudit_b8_1_545.jpg
36 txt_mudit_b8_1_555.jpg
37 txt_mudit_b11_1529.jpg
38 txt_mudit_b8_1_554.jpg
39 txt_mudit_b8_1_742.jpg
40 txt_mudit_b8_1_807.jpg
41 txt_mudit_b8_1_740.jpg
42 txt_mudit_b8_1_741.jpg
43 txt_mudit_b8_1_806.jpg
44 txt_mudit_b11_480.jpg
45 txt_mudit_b11_1339.jpg

In [3]:
#Creating a list(name = data) in which we append a list containing all 6 values( ["Regn number","Chassis number","Name","Engine number","Registration date","Mfg. date"] ) for each image so that data list becomes a 2D list then we convert it to DataFrame using pandas library.
data=[]          
j=0
for pic in list:
    
    img=Image.open('../richajha/Intern/RC//' +pic)          
    en=ImageEnhance.Brightness(img)                         # imagenhance will manupulate image data in a good way
    img=en.enhance(1.2)
    en=ImageEnhance.Color(img)
    img=en.enhance(0.0)
    
    text=pytesseract.image_to_string(img)
    new_str=text.split()                                   # spliting text on the basis of space
    aa=[None]*6                                            #initializing list which hold all 6 values needed from a image
    data.append(aa)
    two=0
    for i in range(len(new_str)-6):

        
    #======================================================================================================================= 
    
    #   Fetching License plate number :-
    
    
        if new_str[i]=='REGN':
            if len(new_str[i+4])<9:
                    a=new_str[i+4]+new_str[i+5]
                    data[j][0]=a
            else:
                data[j][0]=new_str[i+4]
        else:
            if new_str[i]=='REGN.':
                if len(new_str[i+3])<9:
                    a=new_str[i+3]+new_str[i+4]
                    data[j][0]=a
                else:
                    data[j][0]=new_str[i+3]
        if new_str[i]=="Registration":
            if new_str[i+1]=="No.":
                if len(new_str[i+2])<9:
                    a=new_str[i+2]+new_str[i+3]
                    data[j][0]=a
                else:
                    data[j][0]=new_str[i+2]
                
        if 'HR' in new_str[i]:
            data[j][0]==new_str[i]
        
    #=======================================================================================================================  
            
    #    Fetching VIN number (typically 17 digit long) :-
    
    
        if new_str[i]=='CH.' or new_str[i]=='CH' :    
            data[j][1]=new_str[i+3]
            
        if new_str[i]=="Chassis" or new_str[i]=="Chasis":
            if new_str[i+1]=="No.":
                data[j][1]=new_str[i+2]
        
        
    # ===========================================================================================================================================================
      
    #  Fetching Name :-    
        
        if new_str[i]=='NAME' or new_str[i]=='Name' or new_str[i]=='name':
            if '_' or '-' in new_str[i+1]:
                if new_str[i+2]==':' or new_str[i+1]==':.':
                    if new_str[i+3]=='MR' or new_str[i+3]=='mr' or new_str[i+3]=='Mr' or new_str[i+3]=='MR.' or new_str[i+3]=='mr.' or new_str[i+3]=='Mr.':
                        name=new_str[i+4]
                    else:
                        name=new_str[i+3]
                else:
                    if new_str[i+2]=='MR' or new_str[i+2]=='mr' or new_str[i+2]=='Mr' or new_str[i+2]=='MR.' or new_str[i+2]=='mr.' or new_str[i+2]=='Mr.':
                        name=new_str[i+3]
                    else:
                        name=new_str[i+2]
                    
            elif new_str[i+1]==':' or new_str[i+1]==':.':
                    if new_str[i+2]=='MR' or new_str[i+2]=='mr' or new_str[i+2]=='Mr' or new_str[i+2]=='MR.' or new_str[i+2]=='mr.' or new_str[i+2]=='Mr.':
                        name=new_str[i+3]
                    else:
                        name=new_str[i+2]
            elif new_str[i+1]=='MR' or new_str[i+1]=='mr' or new_str[i+1]=='Mr' or new_str[i+1]=='MR.' or new_str[i+1]=='mr.' or new_str[i+1]=='Mr.' :
                name=new_str[i+2]
            
            elif new_str[i-1]=="Owner's":
                name=new_str[i+1]
            elif "&" in new_str[i+1]:
                name=new_str[i+4] #i+4
            else:
                name=new_str[i+1]
            if two==0:
                data[j][2]=name
                two=1
                
                
    #=========== Fetching Engine number  ====================================================================================
        if new_str[i]=='ENO':
            if new_str[i+1]=='-' or new_str[i+1]=='_':
                data[j][3]=new_str[i+3]
            else:
                if new_str[i+2][-1]=='-':
                    a=str(new_str[i+2])+str(new_str[i+3])
                    data[j][3]=a
                else:
                    data[j][3]=new_str[i+2]
        if new_str[i]=="Engine":
            if len(new_str[i+2])<11:
                a=new_str[i+2]+new_str[i+3]
                data[j][3]=a
            else:
                data[j][3]=new_str[i+2]
                


    # ==================================================================================================================
    
    # Fetching Registration date :-
    
        if new_str[i]=="REG." or new_str[i]=="REGN":
            if "DT" in new_str[i+1]:
                if new_str[i+2]==":":
                    reg_date=new_str[i+3]
                else:
                    reg_date=new_str[i+2]
                length=len(reg_date)
                reg_date=reg_date[:length-8]+" / "+reg_date[length-7:length-5]+" / "+reg_date[length-4:]        
            
                data[j][4]=reg_date
        
        
        
    # ===================================================================================================================
    
    #Fetching Mfg. date :-

        if new_str[i]=="Year":
            if new_str[i+1]=="of":
                if "Manu" in new_str[i+2]:
                    manufacture_date=new_str[i+3]
            length=len(manufacture_date)
            manufacture_date=manufacture_date[:length-5]+" / "+manufacture_date[length-4:]
            data[j][5]=manufacture_date
            
        if new_str[i]=="Yr":
            if new_str[i+1]=="of":
                manufacture_date=new_str[i+2]
            length=len(manufacture_date)
            manufacture_date=manufacture_date[:length-5]+" / "+manufacture_date[length-4:]
            data[j][5]=manufacture_date
            
            
            
                 
        if new_str[i]=="Month":
            if new_str[i+3]=="of":
                if new_str[i+4]=="Mfg." or new_str[i+4]=="Mfg" or new_str[i+4]=="Mig." or new_str[i+4]=="Mig":
                    manufacture_date=new_str[i+5]
            length=len(manufacture_date)
            manufacture_date=manufacture_date[:length-5]+"/"+manufacture_date[length-4:]
            data[j][5]=manufacture_date   
        
        if "MFG" in new_str[i]:
            if new_str[i+1]==":":
                manufacture_date=new_str[i+2]
            elif "DT" in new_str[i+1]:
                if new_str[i+2]==":":
                    manufacture_date=new_str[i+3]
                else:
                    manufacture_date=new_str[i+2]
            else:
                manufacture_date=new_str[i+1]
            length=len(manufacture_date)
            manufacture_date=manufacture_date[:length-5]+"/"+manufacture_date[length-4:]
            data[j][5]=manufacture_date
        
        
    j+=1

In [4]:

#Creating DataFrame from 2d list data¶

df=pd.DataFrame(data)
df.columns=["Regn number","Chassis number","Name","Engine number","Registration date","Mfg. date"]
df

,Regn number,Chassis number,Name,Engine number,Registration date,Mfg. date
0,HROGAH1768,MASELMG1800384268,HARISH,7124699Fuel,None,4 / 2016
1,DL3CAX6515,607146KRZW00622,VIKAS,4735IDTI4KRZPBSS19,24 / 04 / 2009,40/2008
2,None,None,None,None,None,None
3,None,None,MOTORS,None,None,None
4,:01,607146KRZW00622,VIKAS,475IDT?4KRZPBEG19,24 / 04 / 2009,/-
5,5387OSNo,None,None,None,None,/CD
6,HR49D0002,None,NATH,Fue!Used,None,9 / 2013
7,DL3CAx6515,607146KRZwWO006272,None,BSCS,2 / 04 / 2009,/-
8,3195“*THPTNP:,None,None,K10BN4590508,30 / 11 / 2013,C/:
9,4987O,None,MANJULA,K10BN7228183,12 / 04 / 2013,02/2043
10,None,None,None,None,None,None
11,HROGS8814,None,Of,None,None,11 / 2008
12,HROGAK2102,MA3FHEB1S00B52684,JITENDER,FuelUsed,None,9 / 2016
13,None,MASE!,MANOJ,M16AN2011764,None,/+
14,None,None,None,None,None,None
15,None,None,None,None,None,None
16,REG.DT:,None,ANIK,None,1 / ns / a013,None
17,:MA3ETDE1S00218363,None,CELERIO,7567094,21 / 07 / 2015,07/2015
18,DL2CAM0993,None,KAMAL,CLASS,1 / /0 / 2010,/-
19,OSNo_:,MA3FDEB1200381622,SAURABH,D13A1833010,03 / 08 / 2012,/CD
20,DL5CJgees,MA3FJEB1S00528720,MEGHNA,01342368228,17 / 05 / 2014,04/2014
21,DL9CAC6215,None,None,D13A0338461,24 / 12 / 2012,C/:
22,DL2CAU7997,MA3FLEB1S00309631,None,COLOR,02 / 08 / 2015,/2
23,DL8CPosNo.,None,None,None,None,/CD
24,DL9CAC1454,None,KUMUDHA,CLASS,18 / 08 / 2011,05/2011
25,None,None,‘SH,DOPTT24S4,None,None
26,DL5CJ6088,MA3FHEB1S00520199,RAJNISH,D13A2235055,06 / 10 / 2013,/‘
27,NO:,MA3EHKD1S00A97129,SACHIN,1774707,07 / 05 / 2016,05/2016
28,DL13CA8614,MA3FHEB1S00593004,OF,S/WID,11 / 02 / 2014,/CD
29,None,None,None,None,None,None
30,"DL9CAE2930""™”",None,KAPOOR,COLOUR,None,None
31,DL8CAH3172,MA3ETDE1S00159552,None,K10BN7417497,24 / 11 / 2014,10/2014
32,None,None,MARUTI,None,None,None
33,HROGP5988,MA3EYD81S00765439,SINGH,None,None,9 / 2006
34,None,None,None,None,None,None
35,None,MA3EED81S00628175,None,F10DN4452456,None,23/01 / 2008
36,None,None,chicle,None,None,None
37,DL8CU7889,None,MAMTA,None,14 / 02 / 2013,M/L
38,HR1O-P-0840,None,Address,©G4EB9M256677_,None,None
39,G.DT:,None,None,None,None,None
40,None,Engine,Address,Month/Yr,None,Se / ting
41,OoSNO.,MAZEEJ91S00127444,HIMANSHU,G16BBN521579,03 / 04 / 2006,03/2006
42,SNOo2,None,OF,None,/ IM / NSHU,C/:
43,None,None,None,None,None,None
44,DL1Cus248,None,None,None,None,None
45,HROGAEB243,MA3EJKO1$00685213,Address,1630003Fuel,None,1 / 2015

In [5]:
#An excel showing the text output for each image.

df.to_csv('excel.csv')

The approach and methodology that used

In this project, Python-tesseract is used. Python-tesseract is an optical character recognition (OCR) tool for python. That is, it will recognize and “read” the text embedded in images. Image enhencement technique is also used for better text fetching such as brightness, color. 
Before starting first of all install pytesseract in anaconda command prompt (pip install pytesseract). Also install tesseract and set the path in a code.

So after applying tesseract, string of text will be available on image. after that split text on the basis on space. Then we will having a list of words. After that we create searching operations for "Regn number","Chassis number","Name","Engine number","Registration date","Mfg. date". after that create dataframe of this fetched data and save it in form of excel file.

In mostly images some data is not given so I used “None” at that place. Also if any data is not given or unable to fetched from the image I printed None.

In this way task can be executed but for better execution we can apply amazon api.